<script setup lang="ts">
import { reactive } from 'vue'
import type { AuditEvent, Experiment } from '@/types/advanced'
import type { Customer, Recommendation } from '@/types/customer'
import { experimentMetrics } from '@/utils/experiments'
const props=defineProps<{experiments:Experiment[];audit:AuditEvent[];customers:Customer[]}>()
const emit=defineEmits<{create:[Experiment];update:[string,Partial<Experiment>];cancel:[string]}>()
const form=reactive({name:'',hypothesis:'',targetSegment:'High-risk customers',startDate:'',endDate:'',assignedAction:'Onboarding' as Recommendation['actionType'],notes:''})
function create(){if(!form.name||!form.hypothesis)return;const highRisk=props.customers.filter(c=>c.riskLevel==='High');emit('create',{id:`exp-${Date.now()}`,...form,controlGroup:highRisk.filter((_,i)=>i%2===1).map(c=>c.id),treatmentGroup:highRisk.filter((_,i)=>i%2===0).map(c=>c.id),customersContacted:0,offersAccepted:0,customersRetained:0,controlCustomersRetained:0,incrementalRetainedRevenue:0,createdAt:new Date().toISOString()});form.name='';form.hypothesis='';form.notes=''}
function cancelExperiment(experiment:Experiment){if(window.confirm(`Cancel and remove “${experiment.name}”? This cannot be undone.`))emit('cancel',experiment.id)}
</script>
<template>
  <div class="experiments page-stack">
    <section class="page-intro"><div><span class="eyebrow">Controlled learning</span><h2>Retention experiments</h2><p>Document hypotheses and control/treatment assignments. RetentionX never labels an observed difference as causal uplift.</p></div></section>
    <section class="notice"><strong>No automatic causal claim</strong><span>A valid comparison requires both control and treatment groups; confounding and statistical uncertainty still require expert review.</span></section>
    <section class="layout">
      <form class="panel form" @submit.prevent="create"><div class="form-heading"><span class="form-icon">+</span><div><h3>Create experiment</h3><p>Define a measurable retention test.</p></div></div><label>Name<input v-model="form.name" required></label><label>Hypothesis<textarea v-model="form.hypothesis" required></textarea></label><label>Target segment<input v-model="form.targetSegment"></label><div class="pair"><label>Start<input v-model="form.startDate" type="date"></label><label>End<input v-model="form.endDate" type="date"></label></div><label>Assigned action<select v-model="form.assignedAction"><option>Support</option><option>Onboarding</option><option>Plan Review</option><option>Renewal</option><option>Payment</option><option>Re-engagement</option></select></label><label>Notes<textarea v-model="form.notes"></textarea></label><button class="create-experiment-button" type="submit">Create experiment <span aria-hidden="true">→</span></button></form>
      <section class="list"><article v-for="e in experiments" :key="e.id" class="panel card"><div class="card-heading"><div><span class="eyebrow">{{e.targetSegment}}</span><h3>{{e.name}}</h3></div><button class="cancel-button" type="button" @click="cancelExperiment(e)">Cancel experiment</button></div><p>{{e.hypothesis}}</p><div class="stats"><span>Control <strong>{{e.controlGroup.length}}</strong></span><span>Treatment <strong>{{e.treatmentGroup.length}}</strong></span><span>Contacted <strong>{{e.customersContacted}}</strong></span><span>Accepted <strong>{{e.offersAccepted}}</strong></span><span>Retained <strong>{{e.customersRetained}}</strong></span><span>Recorded revenue <strong>RM {{e.incrementalRetainedRevenue}}</strong></span></div><div class="recording"><label>Contacted<input type="number" min="0" :value="e.customersContacted" @change="emit('update',e.id,{customersContacted:Number(($event.target as HTMLInputElement).value)})"></label><label>Accepted<input type="number" min="0" :value="e.offersAccepted" @change="emit('update',e.id,{offersAccepted:Number(($event.target as HTMLInputElement).value)})"></label><label>Treatment retained<input type="number" min="0" :value="e.customersRetained" @change="emit('update',e.id,{customersRetained:Number(($event.target as HTMLInputElement).value)})"></label><label>Control retained<input type="number" min="0" :value="e.controlCustomersRetained" @change="emit('update',e.id,{controlCustomersRetained:Number(($event.target as HTMLInputElement).value)})"></label><label>Incremental revenue<input type="number" min="0" :value="e.incrementalRetainedRevenue" @change="emit('update',e.id,{incrementalRetainedRevenue:Number(($event.target as HTMLInputElement).value)})"></label></div><p class="causal">{{experimentMetrics(e).validComparison?'Directional group difference available; not a causal uplift claim.':'Insufficient control/treatment outcome data.'}}</p></article><p v-if="!experiments.length" class="empty">No experiments recorded yet.</p></section>
    </section>
    <section class="panel audit"><h3>Audit log</h3><p v-for="event in audit.slice().reverse().slice(0,20)" :key="event.id"><time>{{new Date(event.timestamp).toLocaleString('en-MY')}}</time><strong>{{event.type}}</strong><span>{{event.detail}} · {{event.actor}}</span></p><div v-if="!audit.length" class="empty">No auditable events recorded.</div></section>
  </div>
</template>
<style scoped>
.experiments{max-width:1400px;margin:auto;padding:32px clamp(20px,3vw,48px) 56px}.notice{display:flex;gap:14px;padding:18px;border-radius:16px;color:var(--color-brown);background:var(--color-peach)}.layout{display:grid;grid-template-columns:380px 1fr;gap:18px}.form,.card,.audit{padding:24px;border-radius:20px}.form{display:grid;gap:13px}.form-heading,.card-heading{display:flex;align-items:center;justify-content:space-between;gap:14px}.form-heading{justify-content:flex-start;padding-bottom:8px;border-bottom:1px solid var(--color-border)}.form-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;color:#171717;background:var(--color-peach);font-size:25px}.form h3,.card h3,.audit h3{margin:0;font:400 27px var(--font-display)}.form-heading p{margin:3px 0 0;color:var(--color-muted);font-size:13px}.form label{font-size:12px;font-weight:700}.form input,.form textarea,.form select{display:block;width:100%;min-height:42px;margin-top:5px;padding:8px 10px;border:1px solid var(--color-border);border-radius:10px}.pair,.stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}.create-experiment-button{display:flex;align-items:center;justify-content:space-between;min-height:50px;margin-top:4px;padding:0 17px;border:0;border-radius:14px;color:#fff;background:#171717;font-size:15px;font-weight:800;box-shadow:0 8px 20px rgba(23,23,23,.14);cursor:pointer}.list{display:grid;gap:14px}.card p{color:var(--color-muted)}.cancel-button{padding:8px 11px;border:1px solid var(--color-danger);border-radius:10px;color:var(--color-danger);background:var(--color-danger-soft);font-weight:700;cursor:pointer}.stats{grid-template-columns:repeat(3,1fr)}.stats span{padding:12px;border-radius:12px;background:var(--color-mist)}.stats strong{display:block;margin-top:4px}.recording{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.recording label{font-size:12px;font-weight:700}.recording input{display:block;width:100%;margin-top:4px;padding:8px;border:1px solid var(--color-border);border-radius:8px}.causal{padding:12px;border-left:3px solid var(--color-brown)}.audit p{display:grid;grid-template-columns:170px 180px 1fr;gap:12px;padding:11px 0;border-top:1px solid var(--color-border)}.audit time,.audit span{color:var(--color-muted)}.empty{padding:30px;text-align:center;color:var(--color-muted)}@media(max-width:850px){.layout{grid-template-columns:1fr}.audit p{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}}@media(max-width:520px){.card-heading{align-items:flex-start;flex-direction:column}.recording,.pair{grid-template-columns:1fr}.cancel-button{width:100%}}
</style>
