import type { CustomerEvent, CustomerInput, Plan } from '@/types/customer'
import type { MergeSummary, SourceId, SourceImport, SourceIssue } from '@/types/dataSource'
import { enrichCustomer } from './riskCalculator'

export const SOURCE_CONFIG: Record<SourceId,{label:string;required:string[];optional:boolean;template:string}> = {
  accounts:{label:'Account master',required:['customerId','companyName','industry','plan','licensedSeats'],optional:false,template:'customerId,companyName,industry,plan,licensedSeats\n1,Example Company,Technology,Pro,35'},
  usage:{label:'Product usage',required:['customerId','eventDate','loginCount','featureUsagePct','activeSeats','featureName','activityType'],optional:true,template:'customerId,eventDate,loginCount,featureUsagePct,activeSeats,featureName,activityType\n1,2026-07-15,24,42,18,Analytics,login'},
  billing:{label:'Billing and payment',required:['customerId','recordDate','monthlyRevenue','paymentStatus','daysLate','renewalDate','plan'],optional:true,template:'customerId,recordDate,monthlyRevenue,paymentStatus,daysLate,renewalDate,plan\n1,2026-07-01,620,Paid,0,2026-09-30,Pro'},
  support:{label:'Customer support',required:['customerId','ticketId','createdAt','status','priority','category','resolutionHours'],optional:true,template:'customerId,ticketId,createdAt,status,priority,category,resolutionHours\n1,T-100,2026-07-10,Open,High,Technical,0'},
  feedback:{label:'Feedback and satisfaction',required:['customerId','submittedAt','satisfactionScore','npsScore','sentiment','comment'],optional:true,template:'customerId,submittedAt,satisfactionScore,npsScore,sentiment,comment\n1,2026-07-12,6,10,Neutral,Needs easier onboarding'},
}
export const sourceIds = Object.keys(SOURCE_CONFIG) as SourceId[]
export const emptySource=(id:SourceId):SourceImport=>({id,fileName:'',status:'Not loaded',rowsDetected:0,validRows:0,invalidRows:0,duplicates:0,importedAt:'',records:[],issues:[]})
function split(line:string){const out:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){out.push(value.trim());value=''}else value+=c}out.push(value.trim());return out}
const validDate=(v:string)=>Boolean(v)&&Number.isFinite(Date.parse(v))
export function parseSourceCsv(id:SourceId,text:string,fileName='import.csv',now=new Date().toISOString()):SourceImport{
  const lines=text.replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').filter(x=>x.trim());const issues:SourceIssue[]=[];if(!lines.length)return{...emptySource(id),fileName,status:'Has issues',issues:[{row:1,message:'The CSV file is empty.'}]}
  const headers=split(lines[0]);const missing=SOURCE_CONFIG[id].required.filter(h=>!headers.includes(h));if(missing.length)return{...emptySource(id),fileName,status:'Has issues',rowsDetected:Math.max(0,lines.length-1),invalidRows:Math.max(0,lines.length-1),issues:[{row:1,message:`Missing required columns: ${missing.join(', ')}`}]}
  const records:Record<string,string|number>[]=[];const seen=new Set<string>();let duplicates=0
  for(let i=1;i<lines.length;i++){const raw=split(lines[i]);const r=Object.fromEntries(headers.map((h,j)=>[h,raw[j]??''])) as Record<string,string|number>;const row=i+1;const cid=Number(r.customerId);if(!Number.isInteger(cid)||cid<=0){issues.push({row,message:'customerId must be a positive integer.'});continue}
    let error='';const dateFields={usage:['eventDate'],billing:['recordDate','renewalDate'],support:['createdAt'],feedback:['submittedAt'],accounts:[]}[id];for(const field of dateFields)if(!validDate(String(r[field]??'')))error=`${field} must be a valid date.`
    const numericFields={accounts:['licensedSeats'],usage:['loginCount','featureUsagePct','activeSeats'],billing:['monthlyRevenue','daysLate'],support:['resolutionHours'],feedback:['satisfactionScore']}[id];for(const field of numericFields){const n=Number(r[field]);if(!Number.isFinite(n)||n<0)error=`${field} must be a non-negative number.`;else r[field]=n}
    if(id==='accounts'&&!['Basic','Pro','Enterprise'].includes(String(r.plan)))error='plan must be Basic, Pro, or Enterprise.'
    if(id==='usage'&&Number(r.featureUsagePct)>100)error='featureUsagePct must be between 0 and 100.'
    if(id==='feedback'){const nps=Number(r.npsScore);r.npsScore=nps;if(Number(r.satisfactionScore)>10||!Number.isFinite(nps)||nps < -100||nps > 100)error='Feedback scores are outside their allowed range.'}
    if(error){issues.push({row,message:error});continue}r.customerId=cid
    const key=id==='accounts'?String(cid):JSON.stringify(r);if(seen.has(key)){duplicates++;issues.push({row,message:'Duplicate record skipped.'});continue}seen.add(key);records.push(r)
  }
  return{id,fileName,status:issues.length?'Has issues':'Ready',rowsDetected:Math.max(0,lines.length-1),validRows:records.length,invalidRows:Math.max(0,lines.length-1-records.length-duplicates),duplicates,importedAt:now,records,issues}
}
const avg=(values:number[],fallback=0)=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):fallback
const latest=(records:Record<string,string|number>[],field:string)=>[...records].sort((a,b)=>String(b[field]).localeCompare(String(a[field])))[0]
export function mergeSources(imports:Record<SourceId,SourceImport>,today=new Date()):MergeSummary{
  const account=imports.accounts.records;const ids=new Set(account.map(r=>Number(r.customerId)));let unmatchedRecords=0;sourceIds.filter(id=>id!=='accounts').forEach(id=>imports[id].records.forEach(r=>{if(!ids.has(Number(r.customerId)))unmatchedRecords++}))
  const events:CustomerEvent[]=[];const customers=account.map(a=>{const id=Number(a.customerId),usage=imports.usage.records.filter(r=>Number(r.customerId)===id),billing=imports.billing.records.filter(r=>Number(r.customerId)===id),support=imports.support.records.filter(r=>Number(r.customerId)===id),feedback=imports.feedback.records.filter(r=>Number(r.customerId)===id);const lastUsage=latest(usage,'eventDate'),lastBilling=latest(billing,'recordDate'),lastFeedback=latest(feedback,'submittedAt');const availability={Account:true,Usage:usage.length>0,Billing:billing.length>0,Support:support.length>0,Feedback:feedback.length>0}
    usage.forEach((r,i)=>events.push({id:`usage-${id}-${i}`,customerId:id,occurredAt:String(r.eventDate),category:'Usage',type:String(r.activityType),title:String(r.activityType)==='decrease'?'Usage decrease':'Product activity',detail:`${r.loginCount} logins · ${r.featureUsagePct}% feature usage.`}))
    billing.forEach((r,i)=>{if(Number(r.daysLate)>0||String(r.paymentStatus).toLowerCase()!=='paid')events.push({id:`billing-${id}-${i}`,customerId:id,occurredAt:String(r.recordDate),category:'Billing',type:String(r.paymentStatus),title:Number(r.daysLate)>0?'Late payment':'Payment update',detail:`${r.paymentStatus}; ${r.daysLate} days late.`})})
    support.forEach((r,i)=>events.push({id:`support-${id}-${i}`,customerId:id,occurredAt:String(r.createdAt),category:'Support',type:String(r.status),title:`Support ticket ${r.ticketId} ${String(r.status).toLowerCase()}`,detail:`${r.priority} priority · ${r.category}.`}))
    feedback.forEach((r,i)=>events.push({id:`feedback-${id}-${i}`,customerId:id,occurredAt:String(r.submittedAt),category:'Feedback',type:String(r.sentiment),title:'Customer feedback received',detail:`Satisfaction ${r.satisfactionScore}/10 · ${r.comment}`.trim()}))
    if(lastBilling?.renewalDate)events.push({id:`renewal-${id}`,customerId:id,occurredAt:String(lastBilling.renewalDate),category:'Billing',type:'Renewal approaching',title:'Subscription renewal date',detail:'Renewal date supplied by billing data.'})
    const renewal=lastBilling?.renewalDate?Math.max(0,Math.ceil((Date.parse(String(lastBilling.renewalDate))-today.getTime())/86400000)):0
    const input:CustomerInput={id,companyName:String(a.companyName),industry:String(a.industry),plan:(String(lastBilling?.plan??a.plan) as Plan),licensedSeats:Number(a.licensedSeats),monthlyRevenue:Number(lastBilling?.monthlyRevenue??0),activeSeats:Number(lastUsage?.activeSeats??0),logins30d:usage.length?avg(usage.map(r=>Number(r.loginCount))):0,previousLogins30d:usage.length>1?Number([...usage].sort((x,y)=>String(y.eventDate).localeCompare(String(x.eventDate)))[1].loginCount):Number(lastUsage?.loginCount??0),featureUsagePct:usage.length?avg(usage.map(r=>Number(r.featureUsagePct))):0,unresolvedTickets:support.filter(r=>!['resolved','closed'].includes(String(r.status).toLowerCase())).length,latePayments90d:billing.filter(r=>Number(r.daysLate)>0).length,satisfactionScore:Number(lastFeedback?.satisfactionScore??0),daysUntilRenewal:renewal,dataAvailability:availability,events:events.filter(e=>e.customerId===id)};return enrichCustomer(input)})
  const loaded=sourceIds.filter(id=>imports[id].status!=='Not loaded'),missingRequiredSources=sourceIds.filter(id=>!SOURCE_CONFIG[id].optional&&!loaded.includes(id)),missingOptionalSources=sourceIds.filter(id=>SOURCE_CONFIG[id].optional&&!loaded.includes(id));const completenessPct=customers.length?Math.round(customers.reduce((s,c)=>s+Object.values(c.dataAvailability!).filter(Boolean).length/5*100,0)/customers.length):0
  return{customers,events,matchedCustomers:customers.filter(c=>Object.values(c.dataAvailability!).filter(Boolean).length>1).length,unmatchedRecords,duplicateCustomerIds:imports.accounts.duplicates,missingRequiredSources,missingOptionalSources,completenessPct,invalidDates:sourceIds.flatMap(id=>imports[id].issues).filter(x=>x.message.includes('date')).length,invalidNumericRanges:sourceIds.flatMap(id=>imports[id].issues).filter(x=>x.message.includes('number')||x.message.includes('range')).length,finalCustomerCount:customers.length}
}
