<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import Sidebar from '@/components/Sidebar.vue'; import TopBar from '@/components/TopBar.vue'; import CommandPalette from '@/components/CommandPalette.vue'
import OverviewView from '@/views/OverviewView.vue'; import CustomersView from '@/views/CustomersView.vue'; import CustomerDetailView from '@/views/CustomerDetailView.vue'; import InsightsView from '@/views/InsightsView.vue'; import RecommendationsView from '@/views/RecommendationsView.vue'; import ScenarioLabView from '@/views/ScenarioLabView.vue'; import DataStudioView from '@/views/DataStudioView.vue'; import ModelTransparencyView from '@/views/ModelTransparencyView.vue'
import type { ViewId } from '@/types/navigation'; import type { RetentionAction, RetentionActionUpdate } from '@/types/action'; import type { Customer } from '@/types/customer'
import { customers as demoCustomers } from '@/data/customers'; import { syntheticHistoricalActions } from '@/data/retentionActions'; import { generateRecommendation } from '@/utils/recommendationEngine'; import { createActionFromRecommendation, latestActionForCustomer, parseStoredActions, updateRetentionAction } from '@/utils/actionManager'

const KEYS={actions:'retentionx-v1-actions',customers:'retentionx-v1-customer-dataset',source:'retentionx-v1-data-source',sidebar:'retentionx-v1-sidebar-collapsed'} as const
const OBSOLETE=['retentionx-action-statuses-v8','retentionx-customer-dataset-v8','retentionx-data-source-v8','retentionx-sidebar-collapsed-v8']
OBSOLETE.forEach((key)=>localStorage.removeItem(key))
function loadCustomers(){try{const raw=localStorage.getItem(KEYS.customers);const value=raw?JSON.parse(raw):null;return Array.isArray(value)?value as Customer[]:demoCustomers}catch{return demoCustomers}}
const activeView=ref<ViewId>('overview'),previousView=ref<ViewId>('customers'),selectedCustomerId=ref<number|null>(null),scenarioCustomerId=ref<number|null>(null),mobileNavOpen=ref(false),commandOpen=ref(false)
const sidebarCollapsed=ref(localStorage.getItem(KEYS.sidebar)==='true'),customers=ref<Customer[]>(loadCustomers()),actions=ref<RetentionAction[]>(parseStoredActions(localStorage.getItem(KEYS.actions),syntheticHistoricalActions)),dataSourceLabel=ref(localStorage.getItem(KEYS.source)??'Curated synthetic demonstration dataset'),toastMessage=ref('');let toastTimer:number|undefined
const recommendations=computed(()=>customers.value.map(generateRecommendation)),selectedCustomer=computed(()=>customers.value.find(c=>c.id===selectedCustomerId.value)??null),selectedRecommendation=computed(()=>recommendations.value.find(r=>r.customerId===selectedCustomerId.value)??null)
const priorityCount=computed(()=>recommendations.value.filter(r=>r.priority!=='Normal'&&!actions.value.some(a=>a.customerId===r.customerId&&a.status!=='Completed')).length)
watch(actions,v=>localStorage.setItem(KEYS.actions,JSON.stringify(v)),{deep:true});watch(customers,v=>localStorage.setItem(KEYS.customers,JSON.stringify(v)),{deep:true});watch(dataSourceLabel,v=>localStorage.setItem(KEYS.source,v));watch(sidebarCollapsed,v=>localStorage.setItem(KEYS.sidebar,String(v)))
const pageMeta=computed(()=>({overview:['Executive workspace','Retention overview','Subscription retention intelligence'],customers:['Portfolio','Customers','Account health and transparent risk signals'],customerDetail:['Customer intelligence',selectedCustomer.value?.companyName??'Customer 360','Evidence, actions and account context'],recommendations:['Workflow','Action Center','Interventions, ownership and recorded outcomes'],scenarios:['Decision lab','Scenario lab','Directional prototype estimates'],insights:['Intelligence','Strategic insights','Portfolio risk and revenue exposure'],data:['Operations','Data studio','Browser-only CSV import'],model:['Governance','Model transparency','Exact heuristic rules and score breakdown']}[activeView.value]??['','','']))
function toast(message:string){toastMessage.value=message;clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toastMessage.value='',2600)}
function navigate(view:ViewId){activeView.value=view;if(view!=='customerDetail')selectedCustomerId.value=null;commandOpen.value=false}
function openCustomer(id:number){if(activeView.value!=='customerDetail')previousView.value=activeView.value;selectedCustomerId.value=id;activeView.value='customerDetail';scrollTo({top:0,behavior:'smooth'})}
function back(){activeView.value=previousView.value==='customerDetail'?'customers':previousView.value;selectedCustomerId.value=null}
function openScenario(id?:number){scenarioCustomerId.value=id??scenarioCustomerId.value;activeView.value='scenarios';selectedCustomerId.value=null}
function createAction(id:number){const customer=customers.value.find(c=>c.id===id),recommendation=recommendations.value.find(r=>r.customerId===id);if(!customer||!recommendation)return;actions.value=[...actions.value,createActionFromRecommendation(recommendation,customer)];activeView.value='recommendations';toast(`Action created for ${customer.companyName}`)}
function updateAction(id:string,update:RetentionActionUpdate){actions.value=actions.value.map(a=>a.id===id?updateRetentionAction(a,update):a);toast('Action updated')}
function applyCustomers(value:Customer[],source:string){customers.value=value;dataSourceLabel.value=source;actions.value=[];navigate('overview');toast(`${value.length} records activated`)}
function resetData(){customers.value=demoCustomers;dataSourceLabel.value='Curated synthetic demonstration dataset';actions.value=syntheticHistoricalActions;navigate('overview');toast('Demo portfolio restored')}
function keyboard(e:KeyboardEvent){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();commandOpen.value=!commandOpen.value}if(e.key==='Escape')commandOpen.value=false}
onMounted(()=>addEventListener('keydown',keyboard));onBeforeUnmount(()=>{removeEventListener('keydown',keyboard);clearTimeout(toastTimer)})
</script>
<template><div class="app-shell">
<Sidebar :active-view="activeView" :mobile-open="mobileNavOpen" :collapsed="sidebarCollapsed" :priority-count="priorityCount" @navigate="navigate" @close="mobileNavOpen=false" @open-command="commandOpen=true" @toggle-collapse="sidebarCollapsed=!sidebarCollapsed"/>
<main class="main-area"><TopBar :eyebrow="pageMeta[0]" :title="pageMeta[1]" :subtitle="pageMeta[2]" :priority-count="priorityCount" @toggle-nav="mobileNavOpen=true" @open-command="commandOpen=true" @review-risk="navigate('recommendations')"/>
<OverviewView v-if="activeView==='overview'" :customers="customers" :recommendations="recommendations" :actions="actions" @open-customer="openCustomer" @view-customers="navigate('customers')" @view-actions="navigate('recommendations')" @view-scenarios="openScenario()"/>
<CustomersView v-else-if="activeView==='customers'" :customers="customers" @open-customer="openCustomer"/>
<CustomerDetailView v-else-if="activeView==='customerDetail'&&selectedCustomer&&selectedRecommendation" :customer="selectedCustomer" :recommendation="selectedRecommendation" :actions="actions.filter(a=>a.customerId===selectedCustomer!.id)" :latest-action="latestActionForCustomer(actions,selectedCustomer.id)" @back="back" @open-scenario="openScenario" @create-action="createAction" @update-action="updateAction"/>
<InsightsView v-else-if="activeView==='insights'" :customers="customers" :actions="actions" @open-customer="openCustomer" @view-actions="navigate('recommendations')"/>
<RecommendationsView v-else-if="activeView==='recommendations'" :customers="customers" :recommendations="recommendations" :actions="actions" @open-customer="openCustomer" @open-scenario="openScenario" @create-action="createAction" @update-action="updateAction"/>
<ScenarioLabView v-else-if="activeView==='scenarios'" :customers="customers" :initial-customer-id="scenarioCustomerId" @open-customer="openCustomer" @create-action="createAction"/>
<ModelTransparencyView v-else-if="activeView==='model'" :customers="customers"/>
<DataStudioView v-else :customers="customers" :source-label="dataSourceLabel" @apply-customers="applyCustomers" @reset-data="resetData"/></main>
<CommandPalette :open="commandOpen" :customers="customers" :active-view="activeView" @close="commandOpen=false" @navigate="navigate" @open-customer="openCustomer"/>
<transition name="toast"><div v-if="toastMessage" class="toast-message" role="status"><span class="toast-icon">✓</span>{{toastMessage}}</div></transition></div></template>
