<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import Sidebar from '@/components/Sidebar.vue'; import TopBar from '@/components/TopBar.vue'; import CommandPalette from '@/components/CommandPalette.vue'
import OverviewView from '@/views/OverviewView.vue'; import CustomersView from '@/views/CustomersView.vue'; import CustomerDetailView from '@/views/CustomerDetailView.vue'; import InsightsView from '@/views/InsightsView.vue'; import RecommendationsView from '@/views/RecommendationsView.vue'; import ScenarioLabView from '@/views/ScenarioLabView.vue'; import DataStudioView from '@/views/DataStudioView.vue'; import ModelTransparencyView from '@/views/ModelTransparencyView.vue'
import ExperimentsView from '@/views/ExperimentsView.vue';import CampaignsView from '@/views/CampaignsView.vue'
import type { ViewId } from '@/types/navigation'; import type { RetentionAction, RetentionActionUpdate } from '@/types/action'; import type { Customer } from '@/types/customer'
import type{AuditEvent,CampaignDraft,Experiment,LogisticArtifact,RiskEngine}from'@/types/advanced'
import { customers as demoCustomers } from '@/data/customers'; import { syntheticHistoricalActions } from '@/data/retentionActions'; import { generateRecommendation } from '@/utils/recommendationEngine'; import { createActionFromRecommendation, latestActionForCustomer, parseStoredActions, updateRetentionAction } from '@/utils/actionManager'
import{applyLogisticModel,loadModelArtifact,resolveEngine}from'@/utils/modelEngine';import{auditEvent,parseAuditLog}from'@/utils/auditLog';import{parseExperiments}from'@/utils/experiments'

const KEYS={actions:'retentionx-v1-actions',customers:'retentionx-v1-customer-dataset',source:'retentionx-v1-data-source',sidebar:'retentionx-v1-sidebar-collapsed',engine:'retentionx-v1-risk-engine',experiments:'retentionx-v1-experiments',campaigns:'retentionx-v1-campaigns',audit:'retentionx-v1-audit'} as const
const OBSOLETE=['retentionx-action-statuses-v8','retentionx-customer-dataset-v8','retentionx-data-source-v8','retentionx-sidebar-collapsed-v8']
OBSOLETE.forEach((key)=>localStorage.removeItem(key))
function loadCustomers(){try{const raw=localStorage.getItem(KEYS.customers);const value=raw?JSON.parse(raw):null;return Array.isArray(value)?value as Customer[]:demoCustomers}catch{return demoCustomers}}
function loadArray<T>(key:string):T[]{try{const x=JSON.parse(localStorage.getItem(key)??'[]');return Array.isArray(x)?x:[]}catch{return[]}}
const activeView=ref<ViewId>('overview'),previousView=ref<ViewId>('customers'),selectedCustomerId=ref<number|null>(null),scenarioCustomerId=ref<number|null>(null),mobileNavOpen=ref(false),commandOpen=ref(false)
const sidebarCollapsed=ref(localStorage.getItem(KEYS.sidebar)==='true'),customers=ref<Customer[]>(loadCustomers()),actions=ref<RetentionAction[]>(parseStoredActions(localStorage.getItem(KEYS.actions),syntheticHistoricalActions)),dataSourceLabel=ref(localStorage.getItem(KEYS.source)??'Curated sample dataset'),toastMessage=ref('');let toastTimer:number|undefined
const requestedEngine=ref<RiskEngine>(localStorage.getItem(KEYS.engine)==='logistic'?'logistic':'heuristic'),artifact=ref<LogisticArtifact|null>(null),experiments=ref<Experiment[]>(parseExperiments(localStorage.getItem(KEYS.experiments))),campaigns=ref<CampaignDraft[]>(loadArray(KEYS.campaigns)),audit=ref<AuditEvent[]>(parseAuditLog(localStorage.getItem(KEYS.audit)))
const activeEngine=computed(()=>resolveEngine(requestedEngine.value,artifact.value)),portfolio=computed(()=>activeEngine.value==='logistic'&&artifact.value?customers.value.map(c=>applyLogisticModel(c,artifact.value!)):customers.value)
const recommendations=computed(()=>portfolio.value.map(generateRecommendation)),selectedCustomer=computed(()=>portfolio.value.find(c=>c.id===selectedCustomerId.value)??null),selectedRecommendation=computed(()=>recommendations.value.find(r=>r.customerId===selectedCustomerId.value)??null)
const priorityCount=computed(()=>recommendations.value.filter(r=>r.priority!=='Normal'&&!actions.value.some(a=>a.customerId===r.customerId&&a.status!=='Completed')).length)
watch(actions,v=>localStorage.setItem(KEYS.actions,JSON.stringify(v)),{deep:true});watch(customers,v=>localStorage.setItem(KEYS.customers,JSON.stringify(v)),{deep:true});watch(dataSourceLabel,v=>localStorage.setItem(KEYS.source,v));watch(sidebarCollapsed,v=>localStorage.setItem(KEYS.sidebar,String(v)));watch(requestedEngine,v=>localStorage.setItem(KEYS.engine,v));watch(experiments,v=>localStorage.setItem(KEYS.experiments,JSON.stringify(v)),{deep:true});watch(campaigns,v=>localStorage.setItem(KEYS.campaigns,JSON.stringify(v)),{deep:true});watch(audit,v=>localStorage.setItem(KEYS.audit,JSON.stringify(v)),{deep:true})
const pageMeta=computed(()=>({overview:['Executive workspace','Retention overview','Subscription retention intelligence'],customers:['Portfolio','Customers','Account health and transparent risk signals'],customerDetail:['Customer intelligence',selectedCustomer.value?.companyName??'Customer 360','Evidence, actions and account context'],recommendations:['Workflow','Action Center','Interventions, ownership and recorded outcomes'],scenarios:['Decision lab','Scenario lab','Directional scenario estimates'],insights:['Intelligence','Strategic insights','Portfolio risk and revenue exposure'],data:['Operations','Data studio','Browser-only CSV import'],model:['Governance','Model transparency','Heuristic and optional trained engine'],experiments:['Learning','Experiments','Control and treatment tracking'],campaigns:['Simulation','Campaigns','Simulated retention outreach']}[activeView.value]??['','','']))
function toast(message:string){toastMessage.value=message;clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toastMessage.value='',2600)}
function log(type:AuditEvent['type'],detail:string){audit.value=[...audit.value,auditEvent(type,detail)]}
function navigate(view:ViewId){activeView.value=view;if(view!=='customerDetail')selectedCustomerId.value=null;commandOpen.value=false}
function openCustomer(id:number){if(activeView.value!=='customerDetail')previousView.value=activeView.value;selectedCustomerId.value=id;activeView.value='customerDetail';scrollTo({top:0,behavior:'smooth'})}
function back(){activeView.value=previousView.value==='customerDetail'?'customers':previousView.value;selectedCustomerId.value=null}
function openScenario(id?:number){scenarioCustomerId.value=id??scenarioCustomerId.value;activeView.value='scenarios';selectedCustomerId.value=null}
function createAction(id:number){const customer=portfolio.value.find(c=>c.id===id),recommendation=recommendations.value.find(r=>r.customerId===id);if(!customer||!recommendation)return;actions.value=[...actions.value,createActionFromRecommendation(recommendation,customer)];log('Action created',`${customer.companyName}: ${recommendation.action}`);activeView.value='recommendations';toast(`Action created for ${customer.companyName}`)}
function cancelAction(id:string){actions.value=actions.value.filter(action=>action.id!==id);toast('Action cancelled and removed')}
function updateAction(id:string,update:RetentionActionUpdate){const before=actions.value.find(a=>a.id===id);actions.value=actions.value.map(a=>a.id===id?updateRetentionAction(a,update):a);if(update.owner&&update.owner!==before?.owner)log('Owner changed',`${before?.owner} → ${update.owner}`);if(update.status&&update.status!==before?.status)log('Status changed',`${before?.status} → ${update.status}`);if(update.customerResponse)log('Customer response recorded',update.customerResponse);if(update.outcome)log('Outcome recorded',update.outcome);if(update.realisedRevenueProtected!==undefined)log('Revenue value edited',String(update.realisedRevenueProtected));toast('Action updated')}
function applyCustomers(value:Customer[],source:string){customers.value=value;dataSourceLabel.value=source;actions.value=[];log('Dataset imported',`${value.length} customers · ${source}`);navigate('overview');toast(`${value.length} records activated`)}
function resetData(){customers.value=demoCustomers;dataSourceLabel.value='Curated sample dataset';actions.value=syntheticHistoricalActions;navigate('overview');toast('Sample portfolio restored')}
function changeEngine(engine:RiskEngine){requestedEngine.value=engine;log('Risk engine changed',engine==='logistic'?(artifact.value?'Trained logistic model':'Logistic requested; heuristic fallback active'):'Transparent heuristic');toast(engine==='logistic'&&!artifact.value?'Artifact unavailable; heuristic fallback active':'Risk engine updated')}
function createExperiment(value:Experiment){experiments.value=[...experiments.value,value];log('Experiment created',value.name);toast('Experiment created')}
function cancelExperiment(id:string){experiments.value=experiments.value.filter(experiment=>experiment.id!==id);toast('Experiment cancelled and removed')}
function updateExperiment(id:string,update:Partial<Experiment>){experiments.value=experiments.value.map(e=>e.id===id?{...e,...update}:e);toast('Experiment results updated')}
function saveCampaign(value:CampaignDraft){campaigns.value=[...campaigns.value,value];toast('Campaign draft saved')}
function simulateCampaign(value:CampaignDraft){campaigns.value=[...campaigns.value,value];log('Campaign simulated',`${value.subject} · ${value.segment}`);toast('Simulation recorded; no email sent')}
function keyboard(e:KeyboardEvent){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();commandOpen.value=!commandOpen.value}if(e.key==='Escape')commandOpen.value=false}
onMounted(async()=>{addEventListener('keydown',keyboard);artifact.value=await loadModelArtifact()});onBeforeUnmount(()=>{removeEventListener('keydown',keyboard);clearTimeout(toastTimer)})
</script>
<template><div class="app-shell">
<Sidebar :active-view="activeView" :mobile-open="mobileNavOpen" :collapsed="sidebarCollapsed" :priority-count="priorityCount" @navigate="navigate" @close="mobileNavOpen=false" @open-command="commandOpen=true" @toggle-collapse="sidebarCollapsed=!sidebarCollapsed"/>
<main class="main-area"><TopBar :eyebrow="pageMeta[0]" :title="pageMeta[1]" :subtitle="pageMeta[2]" :priority-count="priorityCount" @toggle-nav="mobileNavOpen=true" @open-command="commandOpen=true" @review-risk="navigate('recommendations')"/>
<OverviewView v-if="activeView==='overview'" :customers="portfolio" :recommendations="recommendations" :actions="actions" @open-customer="openCustomer" @view-customers="navigate('customers')" @view-actions="navigate('recommendations')" @view-scenarios="openScenario()"/>
<CustomersView v-else-if="activeView==='customers'" :customers="portfolio" @open-customer="openCustomer"/>
<CustomerDetailView v-else-if="activeView==='customerDetail'&&selectedCustomer&&selectedRecommendation" :customer="selectedCustomer" :recommendation="selectedRecommendation" :actions="actions.filter(a=>a.customerId===selectedCustomer!.id)" :latest-action="latestActionForCustomer(actions,selectedCustomer.id)" @back="back" @open-scenario="openScenario" @create-action="createAction" @update-action="updateAction"/>
<InsightsView v-else-if="activeView==='insights'" :customers="portfolio" :actions="actions" @open-customer="openCustomer" @view-actions="navigate('recommendations')"/>
<RecommendationsView v-else-if="activeView==='recommendations'" :customers="portfolio" :recommendations="recommendations" :actions="actions" @open-customer="openCustomer" @open-scenario="openScenario" @create-action="createAction" @update-action="updateAction" @cancel-action="cancelAction"/>
<ScenarioLabView v-else-if="activeView==='scenarios'" :customers="portfolio" :initial-customer-id="scenarioCustomerId" @open-customer="openCustomer" @create-action="createAction"/>
<ModelTransparencyView v-else-if="activeView==='model'" :customers="customers" :requested-engine="requestedEngine" :active-engine="activeEngine" :artifact="artifact" @change-engine="changeEngine"/>
<ExperimentsView v-else-if="activeView==='experiments'" :experiments="experiments" :audit="audit" :customers="portfolio" @create="createExperiment" @update="updateExperiment" @cancel="cancelExperiment"/>
<CampaignsView v-else-if="activeView==='campaigns'" :campaigns="campaigns" :customers="portfolio" @save="saveCampaign" @send="simulateCampaign"/>
<DataStudioView v-else :customers="portfolio" :source-label="dataSourceLabel" @apply-customers="applyCustomers" @reset-data="resetData"/></main>
<CommandPalette :open="commandOpen" :customers="portfolio" :active-view="activeView" @close="commandOpen=false" @navigate="navigate" @open-customer="openCustomer"/>
<transition name="toast"><div v-if="toastMessage" class="toast-message" role="status"><span class="toast-icon">✓</span>{{toastMessage}}</div></transition></div></template>
