create type public.app_role as enum ('admin','customer_success');
create table public.profiles(id uuid primary key references auth.users,on delete cascade,role public.app_role not null default 'customer_success',display_name text);
create table public.customers(id bigint primary key,company_name text not null,payload jsonb not null default '{}');
create table public.customer_events(id uuid primary key default gen_random_uuid(),customer_id bigint references public.customers on delete cascade,occurred_at timestamptz not null,payload jsonb not null default '{}');
create table public.retention_actions(id uuid primary key default gen_random_uuid(),customer_id bigint references public.customers on delete cascade,owner_id uuid references public.profiles,payload jsonb not null default '{}');
create table public.action_notes(id uuid primary key default gen_random_uuid(),action_id uuid references public.retention_actions on delete cascade,author_id uuid references public.profiles,note text not null,created_at timestamptz default now());
create table public.model_runs(id uuid primary key default gen_random_uuid(),created_by uuid references public.profiles,engine text not null,metadata jsonb not null default '{}',created_at timestamptz default now());
create table public.experiments(id uuid primary key default gen_random_uuid(),created_by uuid references public.profiles,payload jsonb not null default '{}',created_at timestamptz default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles,event_type text not null,detail jsonb not null default '{}',created_at timestamptz default now());
alter table public.profiles enable row level security;alter table public.customers enable row level security;alter table public.customer_events enable row level security;alter table public.retention_actions enable row level security;alter table public.action_notes enable row level security;alter table public.model_runs enable row level security;alter table public.experiments enable row level security;alter table public.audit_logs enable row level security;
create function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create policy "users read own profile" on public.profiles for select using(id=auth.uid());
create policy "team reads customers" on public.customers for select using(public.current_role() in ('admin','customer_success'));
create policy "team manages events" on public.customer_events for all using(public.current_role() in ('admin','customer_success')) with check(public.current_role() in ('admin','customer_success'));
create policy "team manages actions" on public.retention_actions for all using(public.current_role() in ('admin','customer_success')) with check(public.current_role() in ('admin','customer_success'));
create policy "team manages notes" on public.action_notes for all using(public.current_role() in ('admin','customer_success')) with check(public.current_role() in ('admin','customer_success'));
create policy "admins manage customers" on public.customers for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "admins manage model runs" on public.model_runs for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "team manages experiments" on public.experiments for all using(public.current_role() in ('admin','customer_success')) with check(public.current_role() in ('admin','customer_success'));
create policy "admins read audit" on public.audit_logs for select using(public.current_role()='admin');
